version: '3'

services:
  go-server:
    container_name: go-server
    build:
      context: ./go-app
      dockerfile: Dockerfile
    volumes:
      - ./logs.txt:/app/logs.txt
    ports:
      - "8080:8080"
      
      
  nginx:
    image: nginx:latest
    privileged: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
