version: '3'

services:
  go-service:
    build: ./go-cookie-service
    environment:
      - PORT=8080

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - go-service
