// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: prime/prime.proto

package __

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsPrimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message int32 `protobuf:"varint,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *IsPrimeRequest) Reset() {
	*x = IsPrimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_prime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsPrimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPrimeRequest) ProtoMessage() {}

func (x *IsPrimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prime_prime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPrimeRequest.ProtoReflect.Descriptor instead.
func (*IsPrimeRequest) Descriptor() ([]byte, []int) {
	return file_prime_prime_proto_rawDescGZIP(), []int{0}
}

func (x *IsPrimeRequest) GetMessage() int32 {
	if x != nil {
		return x.Message
	}
	return 0
}

type IsPrimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *IsPrimeResponse) Reset() {
	*x = IsPrimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_prime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsPrimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPrimeResponse) ProtoMessage() {}

func (x *IsPrimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prime_prime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPrimeResponse.ProtoReflect.Descriptor instead.
func (*IsPrimeResponse) Descriptor() ([]byte, []int) {
	return file_prime_prime_proto_rawDescGZIP(), []int{1}
}

func (x *IsPrimeResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_prime_prime_proto protoreflect.FileDescriptor

var file_prime_prime_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x0e, 0x69, 0x73, 0x50, 0x72,
	0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x0f, 0x69, 0x73, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x32,
	0x5f, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x12, 0x51, 0x0a,
	0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72,
	0x69, 0x6d, 0x65, 0x2e, 0x69, 0x73, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x2e, 0x69, 0x73, 0x50, 0x72, 0x69,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0e, 0x3a, 0x01, 0x2a, 0x22, 0x09, 0x2f, 0x69, 0x73, 0x5f, 0x70, 0x72, 0x69, 0x6d, 0x65,
	0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prime_prime_proto_rawDescOnce sync.Once
	file_prime_prime_proto_rawDescData = file_prime_prime_proto_rawDesc
)

func file_prime_prime_proto_rawDescGZIP() []byte {
	file_prime_prime_proto_rawDescOnce.Do(func() {
		file_prime_prime_proto_rawDescData = protoimpl.X.CompressGZIP(file_prime_prime_proto_rawDescData)
	})
	return file_prime_prime_proto_rawDescData
}

var file_prime_prime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_prime_prime_proto_goTypes = []interface{}{
	(*IsPrimeRequest)(nil),  // 0: prime.isPrimeRequest
	(*IsPrimeResponse)(nil), // 1: prime.isPrimeResponse
}
var file_prime_prime_proto_depIdxs = []int32{
	0, // 0: prime.CheckPrime.CheckPrime:input_type -> prime.isPrimeRequest
	1, // 1: prime.CheckPrime.CheckPrime:output_type -> prime.isPrimeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_prime_prime_proto_init() }
func file_prime_prime_proto_init() {
	if File_prime_prime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prime_prime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsPrimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prime_prime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsPrimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prime_prime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prime_prime_proto_goTypes,
		DependencyIndexes: file_prime_prime_proto_depIdxs,
		MessageInfos:      file_prime_prime_proto_msgTypes,
	}.Build()
	File_prime_prime_proto = out.File
	file_prime_prime_proto_rawDesc = nil
	file_prime_prime_proto_goTypes = nil
	file_prime_prime_proto_depIdxs = nil
}
